### ISSUE TITLE
Code broken

### ISSUE THREAD

**Issue by jetafese** [bmorelli25/simple-nodejs-weather-app#1]
error: { Error: socket hang up
    at createHangUpError (_http_client.js:331:15)
    at Socket.socketOnEnd (_http_client.js:423:23)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) code: 'ECONNRESET' }

**Comment by neelp1** [comment]
did you do `npm install` before `npm start`?

On a similar note, I am getting:
<img width="314" alt="screen shot 2018-05-09 at 4 34 25 pm" src="https://user-images.githubusercontent.com/8394217/39799237-e85c3f06-53a6-11e8-9a03-5a747fd36481.png">

after `npm start` or `node server.js` but it was working before I replaced the place holder for the api key with my api key. Tried to change it back to the place holder but didn't have any effect.

**Comment by jetafese** [comment]
It works now. Just had some hidden framework files from a previous project

**Comment by neelp1** [comment]
Unfortunately I am still getting the same response. I did `git pull` then `npm install` and `npm start` and still getting the same issue. Can't find any useful info in Chrome Dev tools. Did you push up the changes?

**Comment by jetafese** [comment]
Yes I did. Do you have your stuff here on GitHub? I can pull and debug it for you. Sorry I haven't gotten back to you sooner

**Comment by jetafese** [comment]
Also, have you tried http://127.0.0.1:{port number} instead of http://localhost:{port number}?

**Comment by neelp1** [comment]
hey @jetafese I figured out the issue was something to do with port 3000. I changed the port to 3001 and it works perfectly. Probably something to do with my computer. Thanks for the help.

**Comment by zeke333** [comment]
PS C:\PROJECTS\weather-app\weather-website> node server
module.js:549
    throw err;
    ^

Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\PROJECTS\weather-app\weather-website\server.js:3:17)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
